### ISSUE TITLE
Why I can't import Echotorch

### ISSUE THREAD

**Issue by imhithanks** [nschaetti/EchoTorch#19]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-9c001a36283d> in <module>()
----> 1 from echotorch.datasets.NARMADataset import NARMADataset
      2 from torch.utils.data.dataloader import DataLoader

~/anaconda3/lib/python3.7/site-packages/echotorch/__init__.py in <module>()
      3 
      4 # Imports
----> 5 import datasets
      6 import models
      7 import nn

ModuleNotFoundError: No module named 'datasets'

**Comment by dimitrisdermanis** [comment]
Having the same problem here.
This is an attempt to debug. I only import the library and try to initialize an object.

```python:
import torch
import echotorch.nn as etnn

esn = etnn.LiESN()
```

The response is weird.

```bash:
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import echotorch.nn as etnn
  File "~/.local/lib/python3.7/site-packages/echotorch/__init__.py", line 5, in <module>
    import datasets
ModuleNotFoundError: No module named 'datasets'
```

Any ideas on what to do?

**Comment by slarson** [comment]
I had a similar problem on the dev branch, but it was resolved when I worked with the latest released version: https://github.com/nschaetti/EchoTorch/releases/tag/202006291

What version did you see this on?

**Comment by dimitrisdermanis** [comment]
```bash:
$ pip show echotorch
```

```bash:
Name: EchoTorch
Version: 0.1.1
Summary: A Python toolkit for Reservoir Computing.
Home-page: UNKNOWN
Author: Nils Schaetti
Author-email: nils.schaetti@unine.ch
License: GPLv3
Location: /home/dimitris/PycharmProjects/echo_torch/lib/python3.7/site-packages
Requires: torch, numpy, torchvision
Required-by: 
```

Seems like an older version, but this is the one that I 've installed using pip yesterday.
I will try the github version.

**Comment by nschaetti** [comment]
Hi,

I created a new branch for the test release and released a 0.2.3 version after running succesfully all tests.

Can someone test the new branch ? 
pip install -i https://test.pypi.org/simple/ EchoTorch

Regards,

Nils

**Comment by dimitrisdermanis** [comment]
works for me so far
Some of the examples have errors but once they are fixed, examples run as well.

**Comment by SSeanin** [comment]
@nschaetti any plans on releasing the newer version to the main branch of pypi?
pip still installs the 0.1.1 which fails to initialize the module with the said error.
