### ISSUE TITLE
Shape error of a tensor

### ISSUE THREAD

**Issue by Kajiyu** [nschaetti/EchoTorch#5]
Traceback (most recent call last):
  File "switch_attractor_esn.py", line 81, in <module>
    esn(inputs, targets)
  File "/Users/YumaKajihara/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/YumaKajihara/research/ikeg/code/EchoTorch/examples/switch_attractor/echotorch/nn/ESN.py", line 164, in forward
    hidden_states = self.esn_cell(u, y)
  File "/Users/YumaKajihara/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/YumaKajihara/research/ikeg/code/EchoTorch/examples/switch_attractor/echotorch/nn/LiESNCell.py", line 102, in forward
    y_wfdb = self.w_fdb.mv(yt)
RuntimeError: mv: Expected 1-D argument vec, but got 0-D

**Comment by Kajiyu** [comment]
This is one solution:
`y_wfdb = self.w_fdb.mv(yt.view(-1))`

**Comment by nschaetti** [comment]
Old master branch
